[tool.commitizen]
version = "0.0.0"
version_scheme = "semver"
update_changelog_on_bump = true
changelog_incremental = true
# Do not bump major version until we have setup Kubernete
major_version_zero = true
version_files = ["datascience/pyproject.toml", "backend/pyproject.toml"]
bump_message = "build(release): $current_version -> $new_version"
